export const initialState = {
  history: [],
  historyPos: -1,
  allPaths: [],
  selectedPathIndex: null,
  selectedPathId: null,
  tool: 'PEN',
  transformMatrix: null,
  currentPoint: {},
  livePreviewSegment: {},
  selectedPointId: null,
  selectedPointStep: null,
  selectedPointIndex: null,
  isMovingPoint: false,
  isMovingPath: false,
  clientStartPos: {},
  movePathStartPos: {},
  svgPoint: {},
  isFirstPoint: true,
  isDrawing: false,
  nextCurve: {},
  currentSegment: 'L',
  snapToGrid: true,
  hideControls: false,
  viewBox: { x: 24, y: 24 },
  //clientMovePos: {},
  svgCode: '',
  zoom: 20,
};
